[build]
  # No build command needed for static site
  publish = "."

[build.environment]
  # Environment variables (if needed)
  NODE_VERSION = "18"

[[headers]]
  # Apply security headers to all pages
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://unpkg.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' https:; connect-src 'self';"

[[headers]]
  # Cache static assets
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Form handling (for email signup)
[[forms]]
  name = "email-signup"

# Redirect rules (alternative to _redirects file)
[[redirects]]
  from = "/app"
  to = "https://apps.apple.com/app/nestquest"
  status = 302

[[redirects]]
  from = "/download"
  to = "https://apps.apple.com/app/nestquest"
  status = 302

# Force HTTPS and canonical domain
[[redirects]]
  from = "http://nestquest.life/*"
  to = "https://www.nestquest.life/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.nestquest.life/*"
  to = "https://www.nestquest.life/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://nestquest.life/*"
  to = "https://www.nestquest.life/:splat"
  status = 301
  force = true
